### ISSUE TITLE
Change "Schedule" to "Calendar" on Activities Page

### ISSUE THREAD

**Issue by tessawiedmann** [ACMWatUC/acmwuc.github.io#10]
Some people are confused about the "Schedule" button and how it differs from the View my Volunteer Time button. Hopefully changing the phrase to "Calendar" will clear that up

https://github.com/ACMWatUC/acmwuc.github.io/blob/33edf44db495288c0ad011783776819a028ebb07/Activities.html#L103

**Comment by Samwisebuze** [comment]
@tessawiedmann I updated the link text. See Commit 7ed67d5d2e34a727301eed2f0b4d9992285ab546
