### ISSUE TITLE
Update Officers page with 2019-2020 exec board

### ISSUE THREAD

**Issue by dharnesk** [ACMWatUC/acmwuc.github.io#14]
https://github.com/ACMWatUC/acmwuc.github.io/blob/3f01691ac2e04b81a35c63c70a6daaf9ab983801/Officers.html#L85

**Comment by Rooknj** [comment]
![image](https://user-images.githubusercontent.com/30698829/64273777-07468800-cf10-11e9-8072-03f24e7dfb11.png)

Updated officers page
