### ISSUE TITLE
Add Bearcat Coders calendar to website

### ISSUE THREAD

**Issue by dharnesk** [ACMWatUC/acmwuc.github.io#2]
Preferably add it as a separate web page something like http://acmwuc.org/calendar.html

There should be a button labelled "Volunteer Calendar" for it in the Bearcat Coders section

It might also be nice to add a link to it from the navigation bar as well (possibly)

**Comment by Samwisebuze** [comment]
I'm looking into expanding the sidebar to have some utility links and links to IEEE, ACM, RevUC
