### ISSUE TITLE
Change wording for Getting Involved on Bearcat Coders Section

### ISSUE THREAD

**Issue by dharnesk** [ACMWatUC/acmwuc.github.io#3]
Change "Volunteering has started! If you missed the training click 'Get Involved' and review the training slides" 

to 

"Volunteering has started! If you missed the training click 'Get Involved' and review the training slides. They contain volunteer information as well as instructions on how to sign up!"?

**Comment by Samwisebuze** [comment]
Changed wording. See commit 446d9d01a0e6e57132881afa53d94c49ce2e9869
