### ISSUE TITLE
Add a button for Log Your Volunteer Hours for Bearcat Coders

### ISSUE THREAD

**Issue by dharnesk** [ACMWatUC/acmwuc.github.io#4]
Add "Log Your Volunteer Hours" button for Bearcat Coders which links to the following Google form https://goo.gl/forms/XapXd7kx8eCLokHz1

**Comment by Samwisebuze** [comment]
Added button linking to the above URL. see commit c93495e4e745577cdad3b802503317abd9c8fdc1
